---
title: "microsporidians"
author: "Daniel Suh"
date: "`r Sys.Date()`"
output: html_document
---

```{r, load packages, include = F, message = F}
library(tidyverse)
library(magrittr)
library(here)

library(lubridate)
library(textclean)
```

```{r, read data, message=F}
dat_2021 <- read_csv(here("data", "raw", "Microsporidian spore yield 2021.csv"))
dat_2022 <- read_csv(here("data", "raw", "Microsporidian spore yield 2022.csv"))

compiled_data <- read_csv(here("data", "GAponds.master.summary.csv"))

lake_key <- read_csv(here("data", "lake_name_key.csv"))
```

Lots of annoying really text cleaning because apparently strings can be encoded in ways that make them visually the same but not actually identical
```{r}
lake_key %<>% mutate(lake_name = replace_non_ascii(lake_name),
                     lake_abb = replace_non_ascii(lake_abb))
compiled_data %<>% mutate(lakeday = replace_non_ascii(lakeday),
                          lake_id = replace_non_ascii(lake_id))
```



```{r, merge}
dat_2021 %<>% mutate(year="2021")
dat_2022 %<>% mutate(year="2022")
dat <- bind_rows(dat_2021,dat_2022)
summary(dat)
dat %<>% mutate(full_date = paste(Date,year,sep="-"))

dat %<>% mutate(Lake = replace_non_ascii(Lake))
```



```{r, incidence}
incidence <- dat %>% group_by(Lake, full_date) %>% summarize(n=n())
species_incidence <- dat %>% group_by(Lake, full_date, Species) %>% summarize(n=n())
```




```{r}
dat %<>% mutate(st_date = ifelse(is.na(dmy(full_date)),
                                 mdy(Date),
                                 dmy(full_date))) #cannot understand why it is parsing into numeric rather than a date >:(

dat %<>% mutate(st_date = as.Date.numeric(st_date, origin = origin))


compiled_data %<>% mutate(st_date = mdy(date))
```


Join
```{r}
dat %<>%
     mutate(lake_id = Lake,
            across(lake_id, ~  lake_key$lake_name[match(., lake_key$lake_abb)]))


dat$year <- as.numeric(dat$year)

dat %<>% mutate(jday = yday(st_date),
               jday_cum = ifelse(year == 2021,
                                 jday,
                                 jday+365*(year-2021)))

dat %<>% mutate(lakeday = paste(lake_id, jday_cum, sep = "_"))

# compiled_data$lakeday <- gsub(" ", "",compiled_data$lakeday)
# dat$lakeday <- gsub(" ", "", dat$lakeday)


spores_compiled <- left_join(dat, compiled_data)
```

Need to figure out why there are different numbers between spores_compiled and dat if all of the data in dat should be in spores_compiled
```{r}

table(spores_compiled$lake_id)
table(dat$lake_id)

table(spores_compiled$st_date)
table(dat$st_date)

table(spores_compiled$year)
table(dat$year)

table(spores_compiled$lakeday)
table(dat$lakeday)
length(names(table(spores_compiled$lakeday)))
length(names(table(dat$lakeday)))
```

Check to see if missing data are just due to data not yet being entered
```{r}
missing <- which(!names(table(dat$lakeday)) %in% names(table(spores_compiled$lakeday)))
missing_names <- unique(dat$lakeday[missing])

for (i in 1:length(missing_names)){
  print(missing_names[i])
  print(unique(dat$lakeday[missing])[i] %in% compiled_data$lakeday)
  print(unique(dat$lakeday[missing])[i] %in% spores_compiled$lakeday)
}
```


```{r}
#write.csv(spores_compiled, file = here("workshop", "microsporidians.csv"))
```


