---
title: "workshop"
author: "Daniel Suh"
date: "`r Sys.Date()`"
output: html_document
---

```{r, message=F}
library(tidyverse)
library(magrittr)
library(here)
library(ggridges)
library(patchwork)
```



read data
```{r, message = F}
ponds <- read_csv(here("data/GAponds.master.summary.csv"))

dat_2021 <- read_csv(here("data", "raw", "Microsporidian spore yield 2021.csv"))
dat_2022 <- read_csv(here("data", "raw", "Microsporidian spore yield 2022.csv"))

seq_dat <- read_csv(here("data/Microsporidia ID for Alex Strauss - All Samples.csv"))

lake_key <- read_csv(here("data", "lake_name_key.csv"))
```

```{r}
lake_key %<>% mutate(lake_name = replace_non_ascii(lake_name),
                     lake_abb = replace_non_ascii(lake_abb))
ponds %<>% mutate(lakeday = replace_non_ascii(lakeday),
                          lake_id = replace_non_ascii(lake_id))
```


```{r}
dat_2021 %<>% mutate(year="2021")
dat_2022 %<>% mutate(year="2022")
dat <- bind_rows(dat_2021,dat_2022)
summary(dat)
dat %<>% mutate(full_date = paste(Date,year,sep="-"))

dat %<>% mutate(Lake = replace_non_ascii(Lake))

dat %<>% mutate(st_date = ifelse(is.na(dmy(full_date)),
                                 mdy(Date),
                                 dmy(full_date))) #cannot understand why it is parsing into numeric rather than a date >:(

dat %<>% mutate(st_date = as.Date.numeric(st_date, origin = origin))

dat %<>%
     mutate(lake_id = Lake,
            across(lake_id, ~  lake_key$lake_name[match(., lake_key$lake_abb)]))


dat$year <- as.numeric(dat$year)

dat %<>% mutate(jday = yday(st_date),
               jday_cum = ifelse(year == 2021,
                                 jday,
                                 jday+365*(year-2021)))

dat %<>% mutate(lakeday = paste(lake_id, jday_cum, sep = "_"))
```


```{r}
seq_dat %<>% mutate(Key = `Sample ID`)


ponds %<>% mutate(total_abund = dpa.ncount + dam.ncount + dla.ncount + sim.ncount + dia.ncount + cer.ncount + bos.ncount) #make total abundance


#dat %<>% full_join(., seq_dat, by = join_by(Key, Lake, `Avg. Count`, Spores))

#dat %<>% filter(!is.na(Key)) %>% filter(!is.na(colnames(.[1]))) %>% filter(!is.na(Species)) %>% select(-colnames(.[1]))
```



Average spore yield per host species for all parasite species
```{r}

yield <- dat %>% select(Species, Spores) # get spore yield for each species

yield %<>% mutate(species = case_when(Species == "Am" ~ "dam",
                                      Species == "Amb" ~ "dam",
                                      Species == "Bos" ~ "bos",
                                      Species == "Cerio" ~ "cer",
                                      Species == "Dia" ~ "dia",
                                      Species == "La" ~ "dla",
                                      Species == "Lav" ~ "dla",
                                      Species == "Pa" ~ "dpa",
                                      Species == "Simo" ~ "sim"))

yield %<>% group_by(species) %>% summarize(mean_spores = mean(Spores, na.rm=T),
                                           se_spores = sd(Spores, na.rm=T)/sqrt(sum(!is.na(Spores))),
                                           n = sum(!is.na(Spores)))
```


```{r}
yield %>% arrange(desc(mean_spores)) %>% mutate(species=factor(species, levels=unique(species))) %>%
  filter(!is.na(mean_spores)) %>% 
  filter(mean_spores > 0) %>%
  ggplot(.,aes(x=species, y=mean_spores)) + geom_point() + geom_linerange(aes(ymin = mean_spores - se_spores, 
                                                                              ymax = mean_spores + se_spores))
```


```{r}
# get data for each sampling event
dat1 <- ponds %>% select(lakeday, year, lake_id, jday, jday_cum, 
                       dpa.ncount, dam.ncount, dla.ncount, sim.ncount, dia.ncount, cer.ncount, bos.ncount,
                       dpa.ninfect, dam.ninfect, dla.ninfect, sim.ninfect, dia.ninfect, cer.ninfect, bos.ninfect, 
                       dpa.dens, dam.dens, dla.dens, sim.dens, dia.dens, cer.dens, bos.dens, total_abund) %>% distinct() 

#calculate relative abundance and prevalence
dat1 %<>% mutate(dpa.prev = dpa.ninfect/dpa.ncount,
                 dam.prev = dam.ninfect/dam.ncount,
                 dla.prev = dla.ninfect/dla.ncount,
                 sim.prev = sim.ninfect/sim.ncount,
                 dia.prev = dia.ninfect/dia.ncount,
                 cer.prev = cer.ninfect/cer.ncount,
                 bos.prev = bos.ninfect/bos.ncount,
                 dpa.ra = dpa.ncount/total_abund,
                 dam.ra = dam.ncount/total_abund,
                 dla.ra = dla.ncount/total_abund,
                 sim.ra = sim.ncount/total_abund,
                 dia.ra = dia.ncount/total_abund,
                 cer.ra = cer.ncount/total_abund,
                 bos.ra = bos.ncount/total_abund)

#site x event x species
dens <- dat1 %>% pivot_longer(., cols = ends_with("dens"), values_to = "dens") %>% mutate(species = gsub(".dens","",name)) %>% select(lakeday, lake_id, jday_cum, dens, species)

abund <- dat1 %>% pivot_longer(., cols = ends_with("ncount"), values_to = "AB") %>% mutate(species = gsub(".ncount","",name)) %>% select(lakeday, lake_id, jday_cum, AB, species)

rel_abund <- dat1 %>% pivot_longer(., cols = ends_with("ra"), values_to = "RA") %>% mutate(species = gsub(".ra","",name)) %>% select(lakeday, lake_id, jday_cum, RA, species)

prev <- dat1 %>% pivot_longer(., cols = ends_with("prev"), values_to = "prev") %>% mutate(species = gsub(".prev","",name)) %>% select(lakeday, lake_id, jday_cum, prev, species)



#merge
lake_int <- left_join(yield, rel_abund)
lake_int %<>% left_join(., abund)
lake_int %<>% left_join(., dens)
lake_int %<>% left_join(., prev)

#calculate # of spores contributed by each species at each site at each sampling event
lake_int %<>% mutate(rel_spores = ifelse(!is.na(prev),dens*prev*mean_spores, 0))

#calculate total # of spores produced by infected hosts of all species at each site at each sampling event
total_lake_int <- lake_int %>% group_by(lakeday, lake_id, jday_cum) %>% summarize(tot_spores = sum(rel_spores, na.rm = T))

#merge
lake_int %<>% left_join(., total_lake_int)
```

```{r}
p1 <- lake_int %>% arrange(desc(tot_spores)) %>% mutate(lakeday=factor(lakeday, levels=unique(lakeday))) %>%
  filter(species != "bos") %>% 
  filter(tot_spores > 100000000) %>% 
  filter(!lake_id %in% c("NN1", "Chapman", "Memorial", "Oglethorpe")) %>% 
  ggplot(., aes(x = lakeday, y = rel_spores, fill = species)) + 
  geom_bar(stat = "identity", position = "stack") + 
  theme(axis.text.x = element_blank(), axis.title.x = element_blank(), axis.ticks.x = element_blank()) + labs(y = "# of Spores")

p2 <- lake_int %>% arrange(desc(tot_spores)) %>% mutate(lakeday=factor(lakeday, levels=unique(lakeday))) %>%
  filter(species != "bos") %>% 
  filter(tot_spores > 100000000) %>% 
  filter(!lake_id %in% c("NN1", "Chapman", "Memorial", "Oglethorpe")) %>% 
  ggplot(., aes(x = lakeday, y = rel_spores/mean_spores, fill = species)) + 
  geom_bar(stat = "identity", position = "stack") + 
  theme(axis.text.x = element_text(angle = 70, hjust = 1)) + guides(fill = "none") + labs(y = "# of infected individuals")

p1 / p2

```



Site-months - REDO this section
```{r}
site_months <- ponds %>% select(c(full_date:worm)) %>% group_by(st_date, lake_id) %>% distinct()

site_months %<>% mutate(abund = sum(c(dpa.ncount, dam.ncount, dla.ncount, sim.ncount, dia.ncount, cer.ncount, bos.ncount)),
                        inf = sum(c(dpa.ninfect, dam.ninfect, dla.ninfect, sim.ninfect, dia.ninfect, cer.ninfect, bos.ninfect)),
                        prev = inf/abund)

site_months %<>% filter(!lake_id %in% c("Oglethorpe", "NN1", "Memorial", "Chapman"))

site_months %>% ggplot(.,aes(x=jday_cum, y=lake_id, group=lake_id, fill=as.factor(lake_id), height = abund)) + 
  geom_density_ridges_gradient(show.legend = F, stat = "identity") + 
  labs(x = "Day", y ="Lake", title = "Abundance over time")

site_months %>% ggplot(.,aes(x=jday_cum, y=lake_id, group=lake_id, fill=as.factor(lake_id), height = inf)) + 
  geom_density_ridges_gradient(show.legend = F, stat = "identity") + 
  labs(x = "Day", y ="Lake", title = "Incidence over time")

site_months %>% ggplot(.,aes(x=jday_cum, y=lake_id, group=lake_id, fill=as.factor(lake_id), height = prev)) + 
  geom_density_ridges_gradient(show.legend = F, stat = "identity") + 
  labs(x = "Day", y ="Lake", title = "Prevalence over time")

```


```{r}
abundances <- site_months %>% select(c(st_date, lake_id, jday_cum, lakeday, dpa.ncount, dam.ncount, dla.ncount, sim.ncount, dia.ncount, cer.ncount, bos.ncount, abund))
abundances %<>% pivot_longer(.,cols = ends_with("ncount"))
abundances %<>% mutate(prop = value/abund)
```

```{r}
abundances %>% filter(lake_id == "Deans") %>% ggplot(.,aes(x=as.factor(jday_cum), y=prop, fill=name)) + geom_bar(stat = "identity", position="stack")
```


```{r}
mean_abund <- site_months %>% group_by(lake_id) %>% summarize(dpa_prop = mean(dpa.ncount/abund),
                                                              dpa_se = sd(dpa.ncount/abund)/sqrt(n()),
                                                              dam_prop = mean(dam.ncount/abund),
                                                              dam_se = sd(dam.ncount/abund)/sqrt(n()),
                                                              dla_prop = mean(dla.ncount/abund),
                                                              dla_se = sd(dla.ncount/abund)/sqrt(n()),
                                                              sim_prop = mean(sim.ncount/abund),
                                                              sim_se = sd(sim.ncount/abund)/sqrt(n()),
                                                              dia_prop = mean(dia.ncount/abund),
                                                              dia_se = sd(dia.ncount/abund)/sqrt(n()),
                                                              cer_prop = mean(cer.ncount/abund),
                                                              cer_se = sd(cer.ncount/abund)/sqrt(n()),
                                                              bos_prop = mean(bos.ncount/abund),
                                                              bos_se = sd(bos.ncount/abund)/sqrt(n()))
```



